language: node_js
node_js:
  - "6"

cache:
  directories:
    - node_modules
    - $(npm config get prefix)/bin/gulp
    - $(npm config get prefix)/bin/sass-lint
    - $(npm config get prefix)/bin/surge
    - $(npm config get prefix)/bin/tslint

before_install:
  - npm install -g gulp surge sass-lint tslint

install: npm install
script:
  - npm run tslint "app/**/*.ts"
  - npm run sass-lint
  - gulp build --release
after_script:
  - npm run surge
