language: node_js
node_js:
  - "6"

cache:
  directories:
    - node_modules
    - $(npm config get prefix)/bin/ionic
    - $(npm config get prefix)/bin/cordova
    - $(npm config get prefix)/bin/sass-lint
    - $(npm config get prefix)/bin/surge
    - $(npm config get prefix)/bin/tslint

before_install:
  - npm install -g ionic@latest cordova surge sass-lint tslint

install: npm install
before_sript:
  - chmod +x hooks/after_prepare/010_add_platform_class.js
script:
  - npm run tslint "app/**/*.ts"
  - npm run sass-lint
  - ionic platform add browser
  - ionic build browser --release
after_script:
  - npm run surge
